name: Push - run release verifications

concurrency:
  # group name unique for push to push-integ-test
  group: push-e2e-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - joonwonc/license-removal-test-must-fail
  workflow_dispatch:
    inputs:
      base_ref:
        description: ''
        required: true
        default: 'main'
      head_ref:
        description: ''
        required: true
jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: amplify-js
      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build
        with:
          is-prebuild: true  
  dependency_review:
    needs: prebuild
    name: Dependency Review Modified ver.DepRev 
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@e2a5a1afd5d7305b13671410c52a31819ab9fad9 # v4.0.0 https://github.com/actions/checkout/commit/e2a5a1afd5d7305b13671410c52a31819ab9fad9
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@7bbfa034e752445ea40215fff1c3bf9597993d3f # v3.1.3 https://github.com/actions/dependency-review-action/commit/7bbfa034e752445ea40215fff1c3bf9597993d3f
        with: # Warning: Unexpected input(s) 'base_ref', 'head_ref', valid inputs are ['repo-token', 'fail-on-severity', 'fail-on-scopes', 'base-ref', 'head-ref', 'config-file', 'allow-licenses', 'deny-licenses', 'allow-dependencies-licenses', 'allow-ghsas', 'external-repo-token', 'license-check', 'vulnerability-check', 'comment-summary-in-pr', 'deny-packages', 'deny-groups', 'retry-on-snapshot-warnings', 'retry-on-snapshot-warnings-timeout']
          base-ref: ${{ github.event.inputs.base_ref }}
          head-ref: ${{ github.event.inputs.head_ref }}          
          config-file: '.github/dependency-review/dependency-review-config2.yml'
