name: Push - run release verifications

concurrency:
  # group name unique for push to push-integ-test
  group: push-e2e-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - joonwonc/license-removal-test-must-fail
  workflow_dispatch:
    inputs:
      base_ref:
        description: joonwonc/license-removal-test-must-fail
        required: true
        default: 'main'
      head_ref:
        description: joonwonc/license-removal-test-must-fail
        required: true      

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: amplify-js
      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build
        with:
          is-prebuild: true  
  dependency-review:
    needs: prebuild
    uses: ./.github/workflows/callable-dependency-review.yml
    with:
      base-fef: ${{ github.event.inputs.base_ref }}
      head-ref: ${{ github.event.inputs.head_ref }}